apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-inventory-management-svc-solution
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-BSVCHU
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: '__IMAGE__'
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0.11-r1
