# Default values for base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

designerFlowsOperationMode: disabled

license:
  accept: true
  license: L-APEH-BSVCHU
  use: CloudPakForIntegrationNonProduction

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 300Mi

router:
  timeout: 120s

service:
  endpointType: http

useCommonServices: true

version: 11.0.0.11-r1

vcsInfo:
  repoUrl: ""
  branch: ""
